const DATA = {
      // 6 Categories corresponding to Figure 2
      categories: [
        { id: "cat-overall", name: "🏆 Overall Ranking", tasks: 
        ["PanCa-CK56", "PanCa-P63", 
         "PanCa-SYN",  "PanCa-GATA3",
         "PanCa-P16",  "PanCa-CD34",
         "PanCa-PAX8", "PanCa-S100",
         "Lymphoma-CD20",  "PanCa-CK7",
         "PanCa-TTF1", "PanCa-D2-40",
         "PanCa-Ki67","PanCa-P53", 
         "PanCa-PSA",  "Lymphoma-BCL2", 
         "Prostate-Ki-67", "Breast-Ki-67", 
         "Breast-HE2Ki-67", "PanCa-ER", 
         "Breast-ER", "Breast-HE2ER", 
         "PanCa-PR", "Breast-PR",
         "Breast-HE2PR", "PanCa-PD-L1",
         "Breast-HER2", "Breast-HE2HER2",
         "PanCa-P40", "PanCa-NapsinA",
         "Lymphoma-EBER", "Lymphoma-CD10",
         "PanCa-CDX2", "PanCa-CD34",
         "PanCa-CK7", "PanCa-GATA3", 
         "Lymphoma-CD10", "Lymphoma-CD20",
         "PanCa-P40", "PanCa-P63",
         "PanCa-PAX8", "PanCa-PD-L1",
         "PanCa-S100", "PanCa-SYN",
         "PanCa-TTF1", "HNSCC-RecurrenceEvent",
         "HNSCC-MetastasisEvent", "HNSCC-SurvivalStatus",
         "HNSCC-CauseSpecific", "HNSCC-OS",
         "HNSCC-MFS", "HNSCC-RFS",
         "Lymphoma-OS", "Uterus-OS",
         "HNSCC-ProgressionEvent", "HNSCC-TTF",
         "HNSCC-Radiotherapy", "HNSCC-SystemicTherapy",
         "Breast-HER2-pCR", "Breast-TNBC-Residual",
         "Breast-TNBC-pCR", "Breast-RCB",
         "Lymphoma-Subtype", "Breast-Malignant-Benign",
         "Breast-Subtype", "Brain-Subtype",
         "Cervix-CIN", "Testis-infiltration-Pattern",
         "Testis-pT", "Lung-Comp",
         "Lung-Comp(CD3+)", "Lung-Comp(CD20+)",
         "Lung-Comp(CD34+)", "Lung-Comp(CD38+)",
         "Lung-Comp(CD68+)", "Lung-Comp(CDK4+)",
         "Lung-Comp(cyclin+)", "Lung-Comp(D2+)",
         "Lung-Comp(FAP+)", "Lung-Comp(Ki67+)",
         "Lung-Comp(P53+)", "Lung-Comp(SMA+)",
         "HNSCC-Comp", "HNSCC-Comp(CD3+)",
         "HNSCC-Comp(CD8+)", "HNSCC-Comp(FoxP3+)",
         "HNSCC-Comp(HE)", "HNSCC-Comp(PanCK+)",
        ] },
        { id: "cat-stain", name: "IHC Staining Assessment", tasks: [
          "Staining Intensity", "Staining Location", "Staining Quantity"
        ]},
        { id: "cat-ihc", name: "Biomarker Expression"},
        { id: "cat-hist", name: "Diagnosis & Grading"},
        { id: "cat-tissue", name: "Microenvironment"},
        { id: "cat-prog", name: "Progression & Prognosis"},
        { id: "cat-misc", name: "Therapeutic Response"},
      ],

      // Per-task metrics (AUC/ACC/F1). Use consistent model names.
      // Values use {mean, std}. Strings preserved as provided; we parse mean for ranking.
      tasks: {

        "Staining Intensity": [
          { model: "Virchow2", auc: "0.926" },
          { model: "GigaPath", auc: "0.926" },
          { model: "GPFM", auc: "0.924" },
          { model: "UNI", auc: "0.922" },
          { model: "H-optimus-0", auc: "0.920" },
          { model: "Virchow", auc: "0.917" },
          { model: "CONCH", auc: "0.915" },
          { model: "CONCH v1.5", auc: "0.912" },
          { model: "CTransPath", auc: "0.910" },
          { model: "CHIEF", auc: "0.898" },
          { model: "MADELEINE", auc: "0.896" },
          { model: "TITAN", auc: "0.892" },
          { model: "Prov-GigaPath", auc: "0.879" },
          { model: "Phikon", auc: "0.848" }
        ],
        "Staining Location": [
          { model: "GigaPath", auc: "0.964" },
          { model: "Virchow2", auc: "0.964" },
          { model: "GPFM", auc: "0.960" },
          { model: "UNI", auc: "0.960" },
          { model: "H-optimus-0", auc: "0.959" },
          { model: "CONCH", auc: "0.956" },
          { model: "Virchow", auc: "0.956" },
          { model: "CONCH v1.5", auc: "0.955" },
          { model: "CTransPath", auc: "0.947" },
          { model: "MADELEINE", auc: "0.943" },
          { model: "TITAN", auc: "0.941" },
          { model: "CHIEF", auc: "0.938" },
          { model: "Prov-GigaPath", auc: "0.933" },
          { model: "Phikon", auc: "0.879" }
        ],
        "Staining Quantity": [
          { model: "Virchow2", auc: "0.906" },
          { model: "GigaPath", auc: "0.905" },
          { model: "GPFM", auc: "0.903" },
          { model: "UNI", auc: "0.901" },
          { model: "H-optimus-0", auc: "0.898" },
          { model: "Virchow", auc: "0.896" },
          { model: "CONCH", auc: "0.895" },
          { model: "CONCH v1.5", auc: "0.890" },
          { model: "CTransPath", auc: "0.888" },
          { model: "MADELEINE", auc: "0.876" },
          { model: "CHIEF", auc: "0.876" },
          { model: "TITAN", auc: "0.870" },
          { model: "Prov-GigaPath", auc: "0.856" },
          { model: "Phikon", auc: "0.804" }
        ],



























































































































































        "PanCa-AR": [
          { model: "GPFM", auc: "0.998" },
          { model: "UNI", auc: "0.997" },
          { model: "Virchow2", auc: "0.997" },
          { model: "CHIEF", auc: "0.996" },
          { model: "CONCH", auc: "0.996" },
          { model: "CTransPath", auc: "0.995" },
          { model: "GigaPath", auc: "0.992" },
          { model: "CONCH v1.5", auc: "0.992" },
          { model: "Phikon", auc: "0.990" },
          { model: "H-optimus-0", auc: "0.987" },
          { model: "Virchow", auc: "0.985" },
          { model: "MADELEINE", auc: "0.978" },
          { model: "TITAN", auc: "0.978" },
          { model: "Prov-GigaPath", auc: "0.948" },
        ],
        "Breast-H&E-to-HER2": [
          { model: "Virchow2", auc: "0.993" },
          { model: "Phikon", auc: "0.992" },
          { model: "GPFM", auc: "0.991" },
          { model: "UNI", auc: "0.983" },
          { model: "H-optimus-0", auc: "0.981" },
          { model: "GigaPath", auc: "0.978" },
          { model: "Virchow", auc: "0.973" },
          { model: "CTransPath", auc: "0.967" },
          { model: "CONCH", auc: "0.961" },
          { model: "CONCH v1.5", auc: "0.932" },
        ],
        "Breast-HER2": [
          { model: "Virchow2", auc: "0.995" },
          { model: "GPFM", auc: "0.990" },
          { model: "H-optimus-0", auc: "0.989" },
          { model: "Phikon", auc: "0.989" },
          { model: "UNI", auc: "0.988" },
          { model: "Virchow", auc: "0.988" },
          { model: "GigaPath", auc: "0.987" },
          { model: "CONCH", auc: "0.985" },
          { model: "CTransPath", auc: "0.977" },
          { model: "CONCH v1.5", auc: "0.974" },
        ],
        "PanCa-CD34": [
          { model: "UNI", auc: "0.790" },
          { model: "CONCH v1.5", auc: "0.787" },
          { model: "CHIEF", auc: "0.774" },
          { model: "Virchow2", auc: "0.766" },
          { model: "CONCH", auc: "0.765" },
          { model: "GPFM", auc: "0.756" },
          { model: "GigaPath", auc: "0.754" },
          { model: "CTransPath", auc: "0.747" },
          { model: "H-optimus-0", auc: "0.746" },
          { model: "MADELEINE", auc: "0.740" },
          { model: "TITAN", auc: "0.734" },
          { model: "Virchow", auc: "0.734" },
          { model: "Phikon", auc: "0.713" },
          { model: "Prov-GigaPath", auc: "0.651" },
        ],
        "PanCa-CDX2": [
          { model: "Virchow2", auc: "0.998" },
          { model: "MADELEINE", auc: "0.997" },
          { model: "GigaPath", auc: "0.995" },
          { model: "CONCH", auc: "0.993" },
          { model: "CONCH v1.5", auc: "0.992" },
          { model: "Phikon", auc: "0.992" },
          { model: "H-optimus-0", auc: "0.987" },
          { model: "CHIEF", auc: "0.985" },
          { model: "UNI", auc: "0.985" },
          { model: "TITAN", auc: "0.984" },
          { model: "GPFM", auc: "0.983" },
          { model: "Virchow", auc: "0.976" },
          { model: "CTransPath", auc: "0.972" },
          { model: "Prov-GigaPath", auc: "0.938" },
        ],
        "PanCa-CK5/6": [
          { model: "GigaPath", auc: "0.991" },
          { model: "CONCH v1.5", auc: "0.987" },
          { model: "CONCH", auc: "0.986" },
          { model: "H-optimus-0", auc: "0.983" },
          { model: "Virchow", auc: "0.981" },
          { model: "CTransPath", auc: "0.981" },
          { model: "Virchow2", auc: "0.979" },
          { model: "TITAN", auc: "0.977" },
          { model: "GPFM", auc: "0.975" },
          { model: "Phikon", auc: "0.974" },
          { model: "MADELEINE", auc: "0.970" },
          { model: "UNI", auc: "0.970" },
          { model: "CHIEF", auc: "0.945" },
          { model: "Prov-GigaPath", auc: "0.875" },
        ],
        "PanCa-CK7": [
          { model: "GigaPath", auc: "0.960" },
          { model: "Virchow2", auc: "0.952" },
          { model: "Phikon", auc: "0.948" },
          { model: "CTransPath", auc: "0.946" },
          { model: "GPFM", auc: "0.946" },
          { model: "UNI", auc: "0.946" },
          { model: "H-optimus-0", auc: "0.941" },
          { model: "CONCH", auc: "0.938" },
          { model: "Virchow", auc: "0.930" },
          { model: "CONCH v1.5", auc: "0.926" },
          { model: "MADELEINE", auc: "0.916" },
          { model: "CHIEF", auc: "0.889" },
          { model: "TITAN", auc: "0.886" },
          { model: "Prov-GigaPath", auc: "0.866" },
        ],
        "PanCa-D2-40": [
          { model: "CONCH v1.5", auc: "0.790" },
          { model: "Virchow2", auc: "0.790" },
          { model: "CHIEF", auc: "0.768" },
          { model: "UNI", auc: "0.746" },
          { model: "CONCH", auc: "0.740" },
          { model: "TITAN", auc: "0.739" },
          { model: "MADELEINE", auc: "0.729" },
          { model: "GPFM", auc: "0.726" },
          { model: "CTransPath", auc: "0.714" },
          { model: "Phikon", auc: "0.712" },
          { model: "GigaPath", auc: "0.700" },
          { model: "Virchow", auc: "0.698" },
          { model: "H-optimus-0", auc: "0.693" },
          { model: "Prov-GigaPath", auc: "0.640" },
        ],
        "PanCa-ER": [
          { model: "UNI", auc: "0.919" },
          { model: "CONCH", auc: "0.906" },
          { model: "GigaPath", auc: "0.903" },
          { model: "Virchow2", auc: "0.897" },
          { model: "MADELEINE", auc: "0.889" },
          { model: "CONCH v1.5", auc: "0.887" },
          { model: "Phikon", auc: "0.886" },
          { model: "GPFM", auc: "0.880" },
          { model: "CTransPath", auc: "0.865" },
          { model: "H-optimus-0", auc: "0.859" },
          { model: "Virchow", auc: "0.855" },
          { model: "CHIEF", auc: "0.838" },
          { model: "TITAN", auc: "0.825" },
          { model: "Prov-GigaPath", auc: "0.804" },
        ],
        "PanCa-GATA3": [
          { model: "Virchow2", auc: "0.998" },
          { model: "UNI", auc: "0.998" },
          { model: "MADELEINE", auc: "0.994" },
          { model: "GPFM", auc: "0.993" },
          { model: "TITAN", auc: "0.991" },
          { model: "H-optimus-0", auc: "0.991" },
          { model: "CONCH", auc: "0.989" },
          { model: "CHIEF", auc: "0.988" },
          { model: "Phikon", auc: "0.988" },
          { model: "GigaPath", auc: "0.987" },
          { model: "CTransPath", auc: "0.981" },
          { model: "CONCH v1.5", auc: "0.981" },
          { model: "Virchow", auc: "0.972" },
          { model: "Prov-GigaPath", auc: "0.962" },
        ],
        "Breast-ER": [
          { model: "GPFM", auc: "0.994" },
          { model: "H-optimus-0", auc: "0.993" },
          { model: "Virchow2", auc: "0.993" },
          { model: "UNI", auc: "0.993" },
          { model: "Virchow", auc: "0.992" },
          { model: "Phikon", auc: "0.990" },
          { model: "CTransPath", auc: "0.990" },
          { model: "GigaPath", auc: "0.989" },
          { model: "CONCH", auc: "0.987" },
          { model: "CONCH v1.5", auc: "0.978" },
        ],
        "Breast-H&E-to-ER": [
          { model: "GPFM", auc: "0.994" },
          { model: "UNI", auc: "0.993" },
          { model: "Virchow2", auc: "0.993" },
          { model: "H-optimus-0", auc: "0.993" },
          { model: "Virchow", auc: "0.992" },
          { model: "Phikon", auc: "0.990" },
          { model: "CTransPath", auc: "0.990" },
          { model: "GigaPath", auc: "0.989" },
          { model: "CONCH", auc: "0.987" },
          { model: "CONCH v1.5", auc: "0.979" },
        ],
        "Breast-H&E-to-Ki67": [
          { model: "GPFM", auc: "0.991" },
          { model: "Virchow", auc: "0.989" },
          { model: "H-optimus-0", auc: "0.988" },
          { model: "CTransPath", auc: "0.988" },
          { model: "UNI", auc: "0.988" },
          { model: "Phikon", auc: "0.987" },
          { model: "Virchow2", auc: "0.987" },
          { model: "GigaPath", auc: "0.982" },
          { model: "CONCH", auc: "0.981" },
          { model: "CONCH v1.5", auc: "0.969" },
        ],
        "Breast-H&E-to-PR": [
          { model: "GPFM", auc: "0.993" },
          { model: "H-optimus-0", auc: "0.992" },
          { model: "UNI", auc: "0.992" },
          { model: "Virchow", auc: "0.992" },
          { model: "Virchow2", auc: "0.992" },
          { model: "Phikon", auc: "0.988" },
          { model: "CTransPath", auc: "0.987" },
          { model: "CONCH", auc: "0.986" },
          { model: "GigaPath", auc: "0.986" },
          { model: "CONCH v1.5", auc: "0.980" },
        ],
        "Breast-Ki67": [
          { model: "GPFM", auc: "0.991" },
          { model: "CTransPath", auc: "0.988" },
          { model: "UNI", auc: "0.987" },
          { model: "Phikon", auc: "0.987" },
          { model: "Virchow", auc: "0.987" },
          { model: "Virchow2", auc: "0.987" },
          { model: "H-optimus-0", auc: "0.987" },
          { model: "CONCH", auc: "0.982" },
          { model: "GigaPath", auc: "0.982" },
          { model: "CONCH v1.5", auc: "0.970" },
        ],
        "Breast-PR": [
          { model: "GPFM", auc: "0.993" },
          { model: "Virchow2", auc: "0.992" },
          { model: "UNI", auc: "0.992" },
          { model: "H-optimus-0", auc: "0.991" },
          { model: "Virchow", auc: "0.991" },
          { model: "Phikon", auc: "0.988" },
          { model: "CTransPath", auc: "0.987" },
          { model: "CONCH", auc: "0.987" },
          { model: "GigaPath", auc: "0.986" },
          { model: "CONCH v1.5", auc: "0.979" },
        ],
        "PanCa-Ki67": [
          { model: "CONCH v1.5", auc: "0.765" },
          { model: "CTransPath", auc: "0.761" },
          { model: "CONCH", auc: "0.758" },
          { model: "Virchow2", auc: "0.749" },
          { model: "UNI", auc: "0.733" },
          { model: "MADELEINE", auc: "0.731" },
          { model: "Phikon", auc: "0.729" },
          { model: "GigaPath", auc: "0.728" },
          { model: "GPFM", auc: "0.726" },
          { model: "H-optimus-0", auc: "0.722" },
          { model: "Virchow", auc: "0.716" },
          { model: "TITAN", auc: "0.715" },
          { model: "CHIEF", auc: "0.709" },
          { model: "Prov-GigaPath", auc: "0.628" },
        ],
        "PanCa-NapsinA": [
          { model: "GPFM", auc: "0.910" },
          { model: "GigaPath", auc: "0.908" },
          { model: "CONCH v1.5", auc: "0.907" },
          { model: "UNI", auc: "0.905" },
          { model: "MADELEINE", auc: "0.903" },
          { model: "TITAN", auc: "0.902" },
          { model: "CHIEF", auc: "0.886" },
          { model: "Virchow2", auc: "0.885" },
          { model: "CONCH", auc: "0.883" },
          { model: "Phikon", auc: "0.879" },
          { model: "Virchow", auc: "0.872" },
          { model: "H-optimus-0", auc: "0.870" },
          { model: "CTransPath", auc: "0.867" },
          { model: "Prov-GigaPath", auc: "0.796" },
        ],
        "PanCa-P16": [
          { model: "CONCH v1.5", auc: "0.923" },
          { model: "GigaPath", auc: "0.906" },
          { model: "UNI", auc: "0.903" },
          { model: "TITAN", auc: "0.902" },
          { model: "CTransPath", auc: "0.901" },
          { model: "CONCH", auc: "0.900" },
          { model: "Virchow2", auc: "0.900" },
          { model: "GPFM", auc: "0.887" },
          { model: "MADELEINE", auc: "0.883" },
          { model: "Phikon", auc: "0.879" },
          { model: "Virchow", auc: "0.879" },
          { model: "H-optimus-0", auc: "0.872" },
          { model: "CHIEF", auc: "0.794" },
          { model: "Prov-GigaPath", auc: "0.790" },
        ],
        "PanCa-P40": [
          { model: "UNI", auc: "0.980" },
          { model: "Virchow2", auc: "0.980" },
          { model: "CONCH v1.5", auc: "0.980" },
          { model: "GPFM", auc: "0.978" },
          { model: "Phikon", auc: "0.978" },
          { model: "H-optimus-0", auc: "0.977" },
          { model: "CONCH", auc: "0.973" },
          { model: "GigaPath", auc: "0.973" },
          { model: "Virchow", auc: "0.967" },
          { model: "CTransPath", auc: "0.965" },
          { model: "MADELEINE", auc: "0.964" },
          { model: "CHIEF", auc: "0.957" },
          { model: "TITAN", auc: "0.955" },
          { model: "Prov-GigaPath", auc: "0.906" },
        ],
        "PanCa-P53": [
          { model: "CONCH v1.5", auc: "0.971" },
          { model: "Virchow2", auc: "0.960" },
          { model: "CONCH", auc: "0.953" },
          { model: "GigaPath", auc: "0.950" },
          { model: "TITAN", auc: "0.943" },
          { model: "GPFM", auc: "0.935" },
          { model: "UNI", auc: "0.926" },
          { model: "H-optimus-0", auc: "0.904" },
          { model: "Phikon", auc: "0.902" },
          { model: "MADELEINE", auc: "0.882" },
          { model: "Virchow", auc: "0.859" },
          { model: "CTransPath", auc: "0.857" },
          { model: "CHIEF", auc: "0.843" },
          { model: "Prov-GigaPath", auc: "0.713" },
        ],
        "PanCa-P63": [
          { model: "Virchow2", auc: "0.959" },
          { model: "CONCH v1.5", auc: "0.936" },
          { model: "UNI", auc: "0.935" },
          { model: "CONCH", auc: "0.933" },
          { model: "GigaPath", auc: "0.932" },
          { model: "GPFM", auc: "0.918" },
          { model: "CTransPath", auc: "0.910" },
          { model: "H-optimus-0", auc: "0.903" },
          { model: "Virchow", auc: "0.891" },
          { model: "MADELEINE", auc: "0.878" },
          { model: "TITAN", auc: "0.877" },
          { model: "CHIEF", auc: "0.875" },
          { model: "Phikon", auc: "0.852" },
          { model: "Prov-GigaPath", auc: "0.736" },
        ],
        "PanCa-PAX8": [
          { model: "Virchow2", auc: "0.981" },
          { model: "CONCH v1.5", auc: "0.979" },
          { model: "MADELEINE", auc: "0.975" },
          { model: "UNI", auc: "0.974" },
          { model: "GigaPath", auc: "0.970" },
          { model: "CONCH", auc: "0.970" },
          { model: "GPFM", auc: "0.966" },
          { model: "H-optimus-0", auc: "0.965" },
          { model: "TITAN", auc: "0.962" },
          { model: "Virchow", auc: "0.960" },
          { model: "CHIEF", auc: "0.959" },
          { model: "Phikon", auc: "0.955" },
          { model: "CTransPath", auc: "0.949" },
          { model: "Prov-GigaPath", auc: "0.909" },
        ],
        "PanCa-PD-L1": [
          { model: "CONCH v1.5", auc: "0.883" },
          { model: "GigaPath", auc: "0.867" },
          { model: "H-optimus-0", auc: "0.865" },
          { model: "GPFM", auc: "0.860" },
          { model: "Virchow2", auc: "0.855" },
          { model: "CONCH", auc: "0.848" },
          { model: "UNI", auc: "0.843" },
          { model: "CTransPath", auc: "0.834" },
          { model: "Virchow", auc: "0.820" },
          { model: "MADELEINE", auc: "0.807" },
          { model: "TITAN", auc: "0.804" },
          { model: "Phikon", auc: "0.793" },
          { model: "CHIEF", auc: "0.744" },
          { model: "Prov-GigaPath", auc: "0.653" },
        ],
        "PanCa-PR": [
          { model: "Virchow2", auc: "0.942" },
          { model: "CONCH v1.5", auc: "0.916" },
          { model: "CONCH", auc: "0.907" },
          { model: "CTransPath", auc: "0.903" },
          { model: "MADELEINE", auc: "0.890" },
          { model: "TITAN", auc: "0.877" },
          { model: "GigaPath", auc: "0.874" },
          { model: "UNI", auc: "0.873" },
          { model: "GPFM", auc: "0.858" },
          { model: "CHIEF", auc: "0.858" },
          { model: "Virchow", auc: "0.854" },
          { model: "Phikon", auc: "0.853" },
          { model: "H-optimus-0", auc: "0.849" },
          { model: "Prov-GigaPath", auc: "0.762" },
        ],
        "PanCa-PSA": [
          { model: "CONCH v1.5", auc: "0.952" },
          { model: "GigaPath", auc: "0.948" },
          { model: "H-optimus-0", auc: "0.940" },
          { model: "Virchow2", auc: "0.927" },
          { model: "Phikon", auc: "0.926" },
          { model: "GPFM", auc: "0.926" },
          { model: "MADELEINE", auc: "0.925" },
          { model: "CONCH", auc: "0.921" },
          { model: "Virchow", auc: "0.910" },
          { model: "UNI", auc: "0.908" },
          { model: "CHIEF", auc: "0.906" },
          { model: "CTransPath", auc: "0.905" },
          { model: "TITAN", auc: "0.886" },
          { model: "Prov-GigaPath", auc: "0.857" },
        ],
        "PanCa-S100": [
          { model: "CONCH v1.5", auc: "0.872" },
          { model: "MADELEINE", auc: "0.863" },
          { model: "CONCH", auc: "0.857" },
          { model: "Phikon", auc: "0.840" },
          { model: "GPFM", auc: "0.810" },
          { model: "Virchow2", auc: "0.806" },
          { model: "CHIEF", auc: "0.803" },
          { model: "CTransPath", auc: "0.799" },
          { model: "H-optimus-0", auc: "0.799" },
          { model: "GigaPath", auc: "0.797" },
          { model: "TITAN", auc: "0.795" },
          { model: "Prov-GigaPath", auc: "0.788" },
          { model: "Virchow", auc: "0.780" },
          { model: "UNI", auc: "0.774" },
        ],
        "PanCa-SYN": [
          { model: "CONCH v1.5", auc: "0.965" },
          { model: "Virchow", auc: "0.959" },
          { model: "MADELEINE", auc: "0.958" },
          { model: "GigaPath", auc: "0.956" },
          { model: "H-optimus-0", auc: "0.956" },
          { model: "Virchow2", auc: "0.955" },
          { model: "CONCH", auc: "0.952" },
          { model: "TITAN", auc: "0.952" },
          { model: "UNI", auc: "0.951" },
          { model: "GPFM", auc: "0.951" },
          { model: "CHIEF", auc: "0.949" },
          { model: "Prov-GigaPath", auc: "0.946" },
          { model: "Phikon", auc: "0.946" },
          { model: "CTransPath", auc: "0.945" },
        ],
        "PanCa-TTF1": [
          { model: "UNI", auc: "0.995" },
          { model: "GPFM", auc: "0.994" },
          { model: "Virchow2", auc: "0.993" },
          { model: "CONCH v1.5", auc: "0.992" },
          { model: "MADELEINE", auc: "0.988" },
          { model: "GigaPath", auc: "0.988" },
          { model: "CONCH", auc: "0.987" },
          { model: "Virchow", auc: "0.985" },
          { model: "H-optimus-0", auc: "0.976" },
          { model: "CTransPath", auc: "0.972" },
          { model: "TITAN", auc: "0.965" },
          { model: "Phikon", auc: "0.951" },
          { model: "Prov-GigaPath", auc: "0.951" },
          { model: "CHIEF", auc: "0.937" },
        ],
        "Lymphoma-BCL2": [
          { model: "CONCH", auc: "0.966" },
          { model: "CONCH v1.5", auc: "0.956" },
          { model: "Virchow2", auc: "0.955" },
          { model: "CTransPath", auc: "0.948" },
          { model: "Phikon", auc: "0.943" },
          { model: "UNI", auc: "0.941" },
          { model: "CHIEF", auc: "0.938" },
          { model: "H-optimus-0", auc: "0.934" },
          { model: "GPFM", auc: "0.930" },
          { model: "MADELEINE", auc: "0.921" },
          { model: "TITAN", auc: "0.907" },
          { model: "GigaPath", auc: "0.900" },
          { model: "Virchow", auc: "0.887" },
          { model: "Prov-GigaPath", auc: "0.872" },
        ],
        "Lymphoma-CD10": [
          { model: "Virchow2", auc: "0.960" },
          { model: "TITAN", auc: "0.959" },
          { model: "CONCH", auc: "0.958" },
          { model: "MADELEINE", auc: "0.954" },
          { model: "CHIEF", auc: "0.951" },
          { model: "Phikon", auc: "0.946" },
          { model: "CONCH v1.5", auc: "0.945" },
          { model: "H-optimus-0", auc: "0.944" },
          { model: "GPFM", auc: "0.940" },
          { model: "GigaPath", auc: "0.935" },
          { model: "CTransPath", auc: "0.932" },
          { model: "UNI", auc: "0.926" },
          { model: "Virchow", auc: "0.922" },
          { model: "Prov-GigaPath", auc: "0.885" },
        ],
        "Lymphoma-CD20": [
          { model: "TITAN", auc: "0.981" },
          { model: "MADELEINE", auc: "0.967" },
          { model: "CHIEF", auc: "0.965" },
          { model: "Virchow", auc: "0.964" },
          { model: "Phikon", auc: "0.963" },
          { model: "CONCH", auc: "0.961" },
          { model: "GigaPath", auc: "0.961" },
          { model: "CONCH v1.5", auc: "0.959" },
          { model: "CTransPath", auc: "0.958" },
          { model: "Virchow2", auc: "0.958" },
          { model: "UNI", auc: "0.952" },
          { model: "H-optimus-0", auc: "0.952" },
          { model: "GPFM", auc: "0.948" },
          { model: "Prov-GigaPath", auc: "0.928" },
        ],
        "Lymphoma-EBER": [
          { model: "Virchow2", auc: "0.979" },
          { model: "MADELEINE", auc: "0.967" },
          { model: "UNI", auc: "0.962" },
          { model: "TITAN", auc: "0.959" },
          { model: "H-optimus-0", auc: "0.959" },
          { model: "CTransPath", auc: "0.958" },
          { model: "Virchow", auc: "0.958" },
          { model: "GPFM", auc: "0.952" },
          { model: "GigaPath", auc: "0.945" },
          { model: "Prov-GigaPath", auc: "0.935" },
          { model: "CONCH", auc: "0.930" },
          { model: "Phikon", auc: "0.929" },
          { model: "CONCH v1.5", auc: "0.927" },
          { model: "CHIEF", auc: "0.883" },
        ],
        "Lymphoma-Subtype": [
          { model: "Virchow2", auc: "0.998" },
          { model: "CONCH v1.5", auc: "0.995" },
          { model: "Phikon", auc: "0.994" },
          { model: "GigaPath", auc: "0.993" },
          { model: "UNI", auc: "0.993" },
          { model: "H-optimus-0", auc: "0.992" },
          { model: "GPFM", auc: "0.987" },
          { model: "CONCH", auc: "0.981" },
          { model: "TITAN", auc: "0.977" },
          { model: "Virchow", auc: "0.974" },
          { model: "MADELEINE", auc: "0.955" },
          { model: "CTransPath", auc: "0.944" },
          { model: "CHIEF", auc: "0.922" },
          { model: "Prov-GigaPath", auc: "0.740" },
        ],
        "HNSCC-Histotype": [
          { model: "TITAN", auc: "0.780" },
          { model: "Virchow2", auc: "0.776" },
          { model: "Phikon", auc: "0.770" },
          { model: "GPFM", auc: "0.758" },
          { model: "CONCH", auc: "0.749" },
          { model: "Virchow", auc: "0.742" },
          { model: "UNI", auc: "0.739" },
          { model: "CONCH v1.5", auc: "0.726" },
          { model: "GigaPath", auc: "0.721" },
          { model: "H-optimus-0", auc: "0.718" },
          { model: "CTransPath", auc: "0.711" },
          { model: "CHIEF", auc: "0.705" },
          { model: "MADELEINE", auc: "0.656" },
          { model: "Prov-GigaPath", auc: "0.650" },
        ],
        "HNSCC-Histology": [
          { model: "CONCH", auc: "0.781" },
          { model: "GigaPath", auc: "0.763" },
          { model: "Virchow2", auc: "0.760" },
          { model: "TITAN", auc: "0.758" },
          { model: "CONCH v1.5", auc: "0.749" },
          { model: "Virchow", auc: "0.739" },
          { model: "H-optimus-0", auc: "0.735" },
          { model: "UNI", auc: "0.732" },
          { model: "GPFM", auc: "0.723" },
          { model: "Phikon", auc: "0.700" },
          { model: "MADELEINE", auc: "0.683" },
          { model: "CTransPath", auc: "0.681" },
          { model: "CHIEF", auc: "0.667" },
          { model: "Prov-GigaPath", auc: "0.622" },
        ],
        "Cervix-CIN": [
          { model: "Virchow2", auc: "0.662" },
          { model: "UNI", auc: "0.651" },
          { model: "CONCH", auc: "0.616" },
          { model: "GigaPath", auc: "0.615" },
          { model: "CONCH v1.5", auc: "0.605" },
          { model: "MADELEINE", auc: "0.594" },
          { model: "TITAN", auc: "0.584" },
          { model: "Virchow", auc: "0.571" },
          { model: "H-optimus-0", auc: "0.558" },
          { model: "Phikon", auc: "0.538" },
          { model: "CTransPath", auc: "0.537" },
          { model: "GPFM", auc: "0.533" },
          { model: "CHIEF", auc: "0.531" },
          { model: "Prov-GigaPath", auc: "0.498" },
        ],
        "Testis-infiltration-Pattern": [
          { model: "GPFM", auc: "0.667" },
          { model: "CTransPath", auc: "0.641" },
          { model: "CONCH", auc: "0.619" },
          { model: "Phikon", auc: "0.606" },
          { model: "H-optimus-0", auc: "0.603" },
          { model: "CHIEF", auc: "0.603" },
          { model: "GigaPath", auc: "0.578" },
          { model: "TITAN", auc: "0.568" },
          { model: "UNI", auc: "0.559" },
          { model: "CONCH v1.5", auc: "0.556" },
          { model: "Virchow2", auc: "0.556" },
          { model: "MADELEINE", auc: "0.552" },
          { model: "Virchow", auc: "0.470" },
          { model: "Prov-GigaPath", auc: "0.390" },
        ],
        "Testis-pT": [
          { model: "CONCH v1.5", auc: "0.830" },
          { model: "Virchow2", auc: "0.826" },
          { model: "CONCH", auc: "0.774" },
          { model: "TITAN", auc: "0.774" },
          { model: "H-optimus-0", auc: "0.759" },
          { model: "GigaPath", auc: "0.733" },
          { model: "UNI", auc: "0.733" },
          { model: "MADELEINE", auc: "0.719" },
          { model: "GPFM", auc: "0.711" },
          { model: "CHIEF", auc: "0.689" },
          { model: "CTransPath", auc: "0.681" },
          { model: "Phikon", auc: "0.670" },
          { model: "Prov-GigaPath", auc: "0.633" },
          { model: "Virchow", auc: "0.604" },
        ],
        "HNSCC-Surg-OS": [
          { model: "Virchow2", cindex: "0.581" },
          { model: "MADELEINE", cindex: "0.566" },
          { model: "GigaPath", cindex: "0.566" },
          { model: "GPFM", cindex: "0.562" },
          { model: "Phikon", cindex: "0.560" },
          { model: "H-optimus-0", cindex: "0.545" },
          { model: "CHIEF", cindex: "0.530" },
          { model: "TITAN", cindex: "0.530" },
          { model: "CTransPath", cindex: "0.522" },
          { model: "Prov-GigaPath", cindex: "0.518" },
          { model: "Virchow", cindex: "0.518" },
          { model: "UNI", cindex: "0.511" },
          { model: "CONCH v1.5", cindex: "0.505" },
          { model: "CONCH", cindex: "0.496" },
        ],
        "HNSCC-Surg-DSS": [
          { model: "TITAN", cindex: "0.547" },
          { model: "CHIEF", cindex: "0.535" },
          { model: "GPFM", cindex: "0.533" },
          { model: "UNI", cindex: "0.529" },
          { model: "GigaPath", cindex: "0.526" },
          { model: "Virchow2", cindex: "0.525" },
          { model: "Prov-GigaPath", cindex: "0.523" },
          { model: "MADELEINE", cindex: "0.523" },
          { model: "Phikon", cindex: "0.517" },
          { model: "CONCH", cindex: "0.510" },
          { model: "CTransPath", cindex: "0.490" },
          { model: "CONCH v1.5", cindex: "0.485" },
          { model: "Virchow", cindex: "0.468" },
          { model: "H-optimus-0", cindex: "0.460" },
        ],
        "HNSCC-RT-OS": [
          { model: "MADELEINE", cindex: "0.551" },
          { model: "Virchow2", cindex: "0.547" },
          { model: "GigaPath", cindex: "0.546" },
          { model: "Phikon", cindex: "0.544" },
          { model: "Prov-GigaPath", cindex: "0.541" },
          { model: "TITAN", cindex: "0.538" },
          { model: "UNI", cindex: "0.531" },
          { model: "GPFM", cindex: "0.524" },
          { model: "H-optimus-0", cindex: "0.523" },
          { model: "CHIEF", cindex: "0.523" },
          { model: "Virchow", cindex: "0.522" },
          { model: "CONCH v1.5", cindex: "0.521" },
          { model: "CTransPath", cindex: "0.518" },
          { model: "CONCH", cindex: "0.494" },
        ],
        "HNSCC-RT-DSS": [
          { model: "UNI", cindex: "0.532" },
          { model: "H-optimus-0", cindex: "0.531" },
          { model: "Phikon", cindex: "0.529" },
          { model: "GigaPath", cindex: "0.520" },
          { model: "Virchow", cindex: "0.511" },
          { model: "GPFM", cindex: "0.507" },
          { model: "Virchow2", cindex: "0.503" },
          { model: "TITAN", cindex: "0.500" },
          { model: "MADELEINE", cindex: "0.494" },
          { model: "CTransPath", cindex: "0.491" },
          { model: "CHIEF", cindex: "0.483" },
          { model: "CONCH v1.5", cindex: "0.478" },
          { model: "Prov-GigaPath", cindex: "0.477" },
          { model: "CONCH", cindex: "0.472" },
        ],
        "HNSCC-CT-OS": [
          { model: "UNI", cindex: "0.501" },
          { model: "Phikon", cindex: "0.496" },
          { model: "GigaPath", cindex: "0.490" },
          { model: "Prov-GigaPath", cindex: "0.484" },
          { model: "MADELEINE", cindex: "0.484" },
          { model: "CHIEF", cindex: "0.479" },
          { model: "CONCH", cindex: "0.478" },
          { model: "GPFM", cindex: "0.476" },
          { model: "CTransPath", cindex: "0.472" },
          { model: "Virchow", cindex: "0.461" },
          { model: "Virchow2", cindex: "0.460" },
          { model: "TITAN", cindex: "0.457" },
          { model: "H-optimus-0", cindex: "0.440" },
          { model: "CONCH v1.5", cindex: "0.428" },
        ],
        "HNSCC-CT-DSS": [
          { model: "Phikon", cindex: "0.566" },
          { model: "GPFM", cindex: "0.545" },
          { model: "CTransPath", cindex: "0.534" },
          { model: "GigaPath", cindex: "0.525" },
          { model: "UNI", cindex: "0.519" },
          { model: "CHIEF", cindex: "0.515" },
          { model: "Virchow", cindex: "0.489" },
          { model: "TITAN", cindex: "0.489" },
          { model: "CONCH", cindex: "0.488" },
          { model: "MADELEINE", cindex: "0.479" },
          { model: "Virchow2", cindex: "0.468" },
          { model: "CONCH v1.5", cindex: "0.462" },
          { model: "Prov-GigaPath", cindex: "0.462" },
          { model: "H-optimus-0", cindex: "0.459" },
        ],
        "Lymphoma-OS": [
          { model: "Prov-GigaPath", cindex: "0.598" },
          { model: "CONCH v1.5", cindex: "0.586" },
          { model: "Virchow2", cindex: "0.567" },
          { model: "UNI", cindex: "0.567" },
          { model: "H-optimus-0", cindex: "0.561" },
          { model: "GigaPath", cindex: "0.560" },
          { model: "CHIEF", cindex: "0.547" },
          { model: "Phikon", cindex: "0.540" },
          { model: "TITAN", cindex: "0.537" },
          { model: "CONCH", cindex: "0.522" },
          { model: "MADELEINE", cindex: "0.516" },
          { model: "GPFM", cindex: "0.503" },
          { model: "Virchow", cindex: "0.490" },
          { model: "CTransPath", cindex: "0.485" },
        ],
        "Lung-PFS": [
          { model: "MADELEINE", cindex: "0.565" },
          { model: "UNI", cindex: "0.552" },
          { model: "Phikon", cindex: "0.552" },
          { model: "GPFM", cindex: "0.549" },
          { model: "GigaPath", cindex: "0.544" },
          { model: "CONCH", cindex: "0.543" },
          { model: "Virchow2", cindex: "0.542" },
          { model: "Virchow", cindex: "0.542" },
          { model: "H-optimus-0", cindex: "0.541" },
          { model: "TITAN", cindex: "0.537" },
          { model: "CONCH v1.5", cindex: "0.532" },
          { model: "CTransPath", cindex: "0.517" },
          { model: "CHIEF", cindex: "0.511" },
          { model: "Prov-GigaPath", cindex: "0.500" },
        ],
        "Uterus-OS": [
          { model: "TITAN", cindex: "0.630" },
          { model: "GigaPath", cindex: "0.625" },
          { model: "CHIEF", cindex: "0.602" },
          { model: "H-optimus-0", cindex: "0.593" },
          { model: "GPFM", cindex: "0.585" },
          { model: "CONCH", cindex: "0.581" },
          { model: "Phikon", cindex: "0.578" },
          { model: "Virchow2", cindex: "0.563" },
          { model: "UNI", cindex: "0.560" },
          { model: "CONCH v1.5", cindex: "0.559" },
          { model: "MADELEINE", cindex: "0.554" },
          { model: "Virchow", cindex: "0.543" },
          { model: "CTransPath", cindex: "0.536" },
          { model: "Prov-GigaPath", cindex: "0.518" },
        ],

        "HNSCC-Surg-Met": [
          { model: "MADELEINE", auc: "0.700" },
          { model: "GigaPath", auc: "0.683" },
          { model: "Phikon", auc: "0.671" },
          { model: "TITAN", auc: "0.668" },
          { model: "UNI", auc: "0.667" },
          { model: "CONCH", auc: "0.659" },
          { model: "Virchow", auc: "0.627" },
          { model: "Virchow2", auc: "0.604" },
          { model: "GPFM", auc: "0.578" },
          { model: "CHIEF", auc: "0.572" },
          { model: "Prov-GigaPath", auc: "0.545" },
          { model: "H-optimus-0", auc: "0.538" },
          { model: "CONCH v1.5", auc: "0.501" },
          { model: "CTransPath", auc: "0.445" },
        ],
        "HNSCC-Surg-Rec": [
          { model: "TITAN", auc: "0.614" },
          { model: "H-optimus-0", auc: "0.613" },
          { model: "Phikon", auc: "0.564" },
          { model: "MADELEINE", auc: "0.549" },
          { model: "CONCH", auc: "0.532" },
          { model: "GigaPath", auc: "0.526" },
          { model: "UNI", auc: "0.515" },
          { model: "CHIEF", auc: "0.502" },
          { model: "CONCH v1.5", auc: "0.486" },
          { model: "Virchow2", auc: "0.485" },
          { model: "GPFM", auc: "0.477" },
          { model: "Virchow", auc: "0.463" },
          { model: "Prov-GigaPath", auc: "0.448" },
          { model: "CTransPath", auc: "0.440" },
        ],
        "HNSCC-RT-Met": [
          { model: "GigaPath", auc: "0.676" },
          { model: "Virchow2", auc: "0.664" },
          { model: "GPFM", auc: "0.661" },
          { model: "MADELEINE", auc: "0.657" },
          { model: "Phikon", auc: "0.652" },
          { model: "TITAN", auc: "0.641" },
          { model: "Virchow", auc: "0.617" },
          { model: "CONCH v1.5", auc: "0.616" },
          { model: "CTransPath", auc: "0.614" },
          { model: "UNI", auc: "0.613" },
          { model: "H-optimus-0", auc: "0.605" },
          { model: "CONCH", auc: "0.602" },
          { model: "CHIEF", auc: "0.540" },
          { model: "Prov-GigaPath", auc: "0.514" },
        ],
        "HNSCC-RT-Rec": [
          { model: "Phikon", auc: "0.666" },
          { model: "Prov-GigaPath", auc: "0.659" },
          { model: "CTransPath", auc: "0.658" },
          { model: "CHIEF", auc: "0.656" },
          { model: "TITAN", auc: "0.643" },
          { model: "GPFM", auc: "0.641" },
          { model: "GigaPath", auc: "0.641" },
          { model: "MADELEINE", auc: "0.639" },
          { model: "CONCH v1.5", auc: "0.624" },
          { model: "Virchow2", auc: "0.615" },
          { model: "UNI", auc: "0.608" },
          { model: "CONCH", auc: "0.601" },
          { model: "H-optimus-0", auc: "0.559" },
          { model: "Virchow", auc: "0.546" },
        ],
        "HNSCC-CT-Met": [
          { model: "GigaPath", auc: "0.592" },
          { model: "GPFM", auc: "0.584" },
          { model: "Virchow2", auc: "0.579" },
          { model: "CONCH", auc: "0.570" },
          { model: "TITAN", auc: "0.564" },
          { model: "Phikon", auc: "0.530" },
          { model: "MADELEINE", auc: "0.517" },
          { model: "Virchow", auc: "0.502" },
          { model: "UNI", auc: "0.500" },
          { model: "CONCH v1.5", auc: "0.492" },
          { model: "H-optimus-0", auc: "0.481" },
          { model: "CHIEF", auc: "0.476" },
          { model: "CTransPath", auc: "0.469" },
          { model: "Prov-GigaPath", auc: "0.451" },
        ],
        "HNSCC-CT-Rec": [
          { model: "Phikon", auc: "0.649" },
          { model: "CTransPath", auc: "0.593" },
          { model: "GPFM", auc: "0.591" },
          { model: "CONCH", auc: "0.585" },
          { model: "Prov-GigaPath", auc: "0.578" },
          { model: "MADELEINE", auc: "0.571" },
          { model: "CONCH v1.5", auc: "0.569" },
          { model: "CHIEF", auc: "0.564" },
          { model: "TITAN", auc: "0.562" },
          { model: "Virchow2", auc: "0.550" },
          { model: "GigaPath", auc: "0.549" },
          { model: "UNI", auc: "0.540" },
          { model: "H-optimus-0", auc: "0.539" },
          { model: "Virchow", auc: "0.528" },
        ],



        "Breast-RCB": [
          { model: "MADELEINE", auc: "0.766" },
          { model: "CONCH", auc: "0.747" },
          { model: "CHIEF", auc: "0.734" },
          { model: "GPFM", auc: "0.727" },
          { model: "Virchow", auc: "0.719" },
          { model: "UNI", auc: "0.715" },
          { model: "TITAN", auc: "0.713" },
          { model: "Virchow2", auc: "0.710" },
          { model: "GigaPath", auc: "0.704" },
          { model: "CTransPath", auc: "0.704" },
          { model: "Prov-GigaPath", auc: "0.699" },
          { model: "H-optimus-0", auc: "0.691" },
          { model: "Phikon", auc: "0.682" },
          { model: "CONCH v1.5", auc: "0.677" },
        ],
        "HNSCC-Surg-Met": [
          { model: "MADELEINE", auc: "0.700" },
          { model: "GigaPath", auc: "0.683" },
          { model: "Phikon", auc: "0.671" },
          { model: "TITAN", auc: "0.668" },
          { model: "UNI", auc: "0.667" },
          { model: "CONCH", auc: "0.659" },
          { model: "Virchow", auc: "0.627" },
          { model: "Virchow2", auc: "0.604" },
          { model: "GPFM", auc: "0.578" },
          { model: "CHIEF", auc: "0.572" },
          { model: "Prov-GigaPath", auc: "0.545" },
          { model: "H-optimus-0", auc: "0.538" },
          { model: "CONCH v1.5", auc: "0.501" },
          { model: "CTransPath", auc: "0.445" },
        ],
        "HNSCC-Surg-Rec": [
          { model: "TITAN", auc: "0.614" },
          { model: "H-optimus-0", auc: "0.613" },
          { model: "Phikon", auc: "0.564" },
          { model: "MADELEINE", auc: "0.549" },
          { model: "CONCH", auc: "0.532" },
          { model: "GigaPath", auc: "0.526" },
          { model: "UNI", auc: "0.515" },
          { model: "CHIEF", auc: "0.502" },
          { model: "CONCH v1.5", auc: "0.486" },
          { model: "Virchow2", auc: "0.485" },
          { model: "GPFM", auc: "0.477" },
          { model: "Virchow", auc: "0.463" },
          { model: "Prov-GigaPath", auc: "0.448" },
          { model: "CTransPath", auc: "0.440" },
        ],
        "HNSCC-RT-Met": [
          { model: "GigaPath", auc: "0.676" },
          { model: "Virchow2", auc: "0.664" },
          { model: "GPFM", auc: "0.661" },
          { model: "MADELEINE", auc: "0.657" },
          { model: "Phikon", auc: "0.652" },
          { model: "TITAN", auc: "0.641" },
          { model: "Virchow", auc: "0.617" },
          { model: "CONCH v1.5", auc: "0.616" },
          { model: "CTransPath", auc: "0.614" },
          { model: "UNI", auc: "0.613" },
          { model: "H-optimus-0", auc: "0.605" },
          { model: "CONCH", auc: "0.602" },
          { model: "CHIEF", auc: "0.540" },
          { model: "Prov-GigaPath", auc: "0.514" },
        ],
        "HNSCC-RT-Rec": [
          { model: "Phikon", auc: "0.666" },
          { model: "Prov-GigaPath", auc: "0.659" },
          { model: "CTransPath", auc: "0.658" },
          { model: "CHIEF", auc: "0.656" },
          { model: "TITAN", auc: "0.643" },
          { model: "GPFM", auc: "0.641" },
          { model: "GigaPath", auc: "0.641" },
          { model: "MADELEINE", auc: "0.639" },
          { model: "CONCH v1.5", auc: "0.624" },
          { model: "Virchow2", auc: "0.615" },
          { model: "UNI", auc: "0.608" },
          { model: "CONCH", auc: "0.601" },
          { model: "H-optimus-0", auc: "0.559" },
          { model: "Virchow", auc: "0.546" },
        ],
        "HNSCC-CT-Met": [
          { model: "GigaPath", auc: "0.592" },
          { model: "GPFM", auc: "0.584" },
          { model: "Virchow2", auc: "0.579" },
          { model: "CONCH", auc: "0.570" },
          { model: "TITAN", auc: "0.564" },
          { model: "Phikon", auc: "0.530" },
          { model: "MADELEINE", auc: "0.517" },
          { model: "Virchow", auc: "0.502" },
          { model: "UNI", auc: "0.500" },
          { model: "CONCH v1.5", auc: "0.492" },
          { model: "H-optimus-0", auc: "0.481" },
          { model: "CHIEF", auc: "0.476" },
          { model: "CTransPath", auc: "0.469" },
          { model: "Prov-GigaPath", auc: "0.451" },
        ],
        "HNSCC-CT-Rec": [
          { model: "Phikon", auc: "0.649" },
          { model: "CTransPath", auc: "0.593" },
          { model: "GPFM", auc: "0.591" },
          { model: "CONCH", auc: "0.585" },
          { model: "Prov-GigaPath", auc: "0.578" },
          { model: "MADELEINE", auc: "0.571" },
          { model: "CONCH v1.5", auc: "0.569" },
          { model: "CHIEF", auc: "0.564" },
          { model: "TITAN", auc: "0.562" },
          { model: "Virchow2", auc: "0.550" },
          { model: "GigaPath", auc: "0.549" },
          { model: "UNI", auc: "0.540" },
          { model: "H-optimus-0", auc: "0.539" },
          { model: "Virchow", auc: "0.528" },
        ],
        "Breast-TNBC-pCR": [
          { model: "CONCH v1.5", auc: "0.811" },
          { model: "Virchow2", auc: "0.724" },
          { model: "UNI", auc: "0.723" },
          { model: "GigaPath", auc: "0.711" },
          { model: "GPFM", auc: "0.710" },
          { model: "Phikon", auc: "0.709" },
          { model: "CONCH", auc: "0.705" },
          { model: "TITAN", auc: "0.692" },
          { model: "H-optimus-0", auc: "0.682" },
          { model: "CHIEF", auc: "0.676" },
          { model: "Virchow", auc: "0.661" },
          { model: "CTransPath", auc: "0.659" },
          { model: "MADELEINE", auc: "0.642" },
          { model: "Prov-GigaPath", auc: "0.518" },
        ],
        "Breast-HER2-pCR": [
          { model: "Prov-GigaPath", auc: "0.878" },
          { model: "GPFM", auc: "0.849" },
          { model: "MADELEINE", auc: "0.848" },
          { model: "CHIEF", auc: "0.829" },
          { model: "Phikon", auc: "0.820" },
          { model: "UNI", auc: "0.816" },
          { model: "CTransPath", auc: "0.806" },
          { model: "CONCH", auc: "0.786" },
          { model: "CONCH v1.5", auc: "0.784" },
          { model: "Virchow", auc: "0.777" },
          { model: "H-optimus-0", auc: "0.776" },
          { model: "Virchow2", auc: "0.775" },
          { model: "GigaPath", auc: "0.744" },
          { model: "TITAN", auc: "0.728" },
        ],
        "Lung-Immunotherapy": [
          { model: "MADELEINE", auc: "0.707" },
          { model: "TITAN", auc: "0.702" },
          { model: "Phikon", auc: "0.693" },
          { model: "CONCH", auc: "0.685" },
          { model: "CTransPath", auc: "0.679" },
          { model: "Virchow", auc: "0.677" },
          { model: "CONCH v1.5", auc: "0.671" },
          { model: "H-optimus-0", auc: "0.662" },
          { model: "GigaPath", auc: "0.644" },
          { model: "UNI", auc: "0.643" },
          { model: "Virchow2", auc: "0.642" },
          { model: "GPFM", auc: "0.640" },
          { model: "CHIEF", auc: "0.618" },
          { model: "Prov-GigaPath", auc: "0.563" },
        ],
        "Lung-Comp": [
          { model: "GPFM", auc: "0.992" },
          { model: "Virchow2", auc: "0.992" },
          { model: "H-optimus-0", auc: "0.991" },
          { model: "Virchow", auc: "0.990" },
          { model: "UNI", auc: "0.989" },
          { model: "Phikon", auc: "0.989" },
          { model: "GigaPath", auc: "0.987" },
          { model: "CTransPath", auc: "0.986" },
          { model: "CONCH", auc: "0.979" },
          { model: "CONCH v1.5", auc: "0.978" },
        ],
        "Lung-Comp(CD3+)": [
          { model: "GPFM", auc: "0.997" },
          { model: "Virchow2", auc: "0.997" },
          { model: "UNI", auc: "0.996" },
          { model: "H-optimus-0", auc: "0.996" },
          { model: "GigaPath", auc: "0.996" },
          { model: "Virchow", auc: "0.995" },
          { model: "Phikon", auc: "0.995" },
          { model: "CTransPath", auc: "0.993" },
          { model: "CONCH", auc: "0.988" },
          { model: "CONCH v1.5", auc: "0.986" },
        ],
        "Lung-Comp(CD38+)": [
          { model: "GPFM", auc: "0.995" },
          { model: "H-optimus-0", auc: "0.995" },
          { model: "Virchow2", auc: "0.994" },
          { model: "UNI", auc: "0.993" },
          { model: "Virchow", auc: "0.992" },
          { model: "GigaPath", auc: "0.992" },
          { model: "Phikon", auc: "0.992" },
          { model: "CTransPath", auc: "0.986" },
          { model: "CONCH", auc: "0.981" },
          { model: "CONCH v1.5", auc: "0.978" },
        ],
        "Lung-Comp(SMA+)": [
          { model: "GPFM", auc: "0.997" },
          { model: "H-optimus-0", auc: "0.997" },
          { model: "Virchow2", auc: "0.997" },
          { model: "UNI", auc: "0.997" },
          { model: "Phikon", auc: "0.996" },
          { model: "GigaPath", auc: "0.995" },
          { model: "Virchow", auc: "0.995" },
          { model: "CTransPath", auc: "0.992" },
          { model: "CONCH", auc: "0.986" },
          { model: "CONCH v1.5", auc: "0.984" },
        ],
        "HNSCC-Comp": [
          { model: "Virchow2", auc: "0.996" },
          { model: "H-optimus-0", auc: "0.994" },
          { model: "GPFM", auc: "0.993" },
          { model: "GigaPath", auc: "0.993" },
          { model: "UNI", auc: "0.993" },
          { model: "Virchow", auc: "0.993" },
          { model: "Phikon", auc: "0.985" },
          { model: "CONCH", auc: "0.977" },
          { model: "CONCH v1.5", auc: "0.974" },
          { model: "CTransPath", auc: "0.967" },
        ],
        "HNSCC-Comp(CD3+)": [
          { model: "Virchow2", auc: "0.978" },
          { model: "GigaPath", auc: "0.969" },
          { model: "UNI", auc: "0.967" },
          { model: "GPFM", auc: "0.965" },
          { model: "CONCH v1.5", auc: "0.965" },
          { model: "Phikon", auc: "0.963" },
          { model: "Virchow", auc: "0.960" },
          { model: "CONCH", auc: "0.956" },
          { model: "H-optimus-0", auc: "0.955" },
          { model: "CTransPath", auc: "0.946" },
        ],
        "HNSCC-Comp(CD8+)": [
          { model: "Virchow2", auc: "0.978" },
          { model: "GPFM", auc: "0.977" },
          { model: "UNI", auc: "0.974" },
          { model: "Phikon", auc: "0.969" },
          { model: "CONCH", auc: "0.960" },
          { model: "CONCH v1.5", auc: "0.958" },
          { model: "Virchow", auc: "0.957" },
          { model: "GigaPath", auc: "0.953" },
          { model: "H-optimus-0", auc: "0.948" },
          { model: "CTransPath", auc: "0.944" },
        ],
        "HNSCC-Comp(FoxP3+)": [
          { model: "Virchow2", auc: "0.987" },
          { model: "GPFM", auc: "0.981" },
          { model: "UNI", auc: "0.975" },
          { model: "Virchow", auc: "0.966" },
          { model: "GigaPath", auc: "0.964" },
          { model: "Phikon", auc: "0.959" },
          { model: "H-optimus-0", auc: "0.958" },
          { model: "CTransPath", auc: "0.954" },
          { model: "CONCH", auc: "0.952" },
          { model: "CONCH v1.5", auc: "0.939" },
        ],
        "HNSCC-Comp(HE)": [
          { model: "Virchow2", auc: "0.978" },
          { model: "GPFM", auc: "0.975" },
          { model: "UNI", auc: "0.973" },
          { model: "Virchow", auc: "0.970" },
          { model: "GigaPath", auc: "0.969" },
          { model: "Phikon", auc: "0.968" },
          { model: "CTransPath", auc: "0.961" },
          { model: "H-optimus-0", auc: "0.961" },
          { model: "CONCH", auc: "0.948" },
          { model: "CONCH v1.5", auc: "0.941" },
        ],
        "HNSCC-Comp(PanCK+)": [
          { model: "Virchow2", auc: "0.977" },
          { model: "Phikon", auc: "0.977" },
          { model: "UNI", auc: "0.975" },
          { model: "Virchow", auc: "0.973" },
          { model: "GPFM", auc: "0.969" },
          { model: "GigaPath", auc: "0.964" },
          { model: "H-optimus-0", auc: "0.958" },
          { model: "CTransPath", auc: "0.956" },
          { model: "CONCH", auc: "0.955" },
          { model: "CONCH v1.5", auc: "0.947" },
        ],
},

      // Foundation models overview table
      foundationModels: [
        { name: "UNI", level: "Patch", ihcTrain: "✗", venue: "Nature Medicine", date: "2024.03", ssl: "DINOv2", arch: "ViT-L/16", params: "307M", wsis: "100K", url: "https://www.nature.com/articles/s41591-024-02857-3"},
        { name: "Virchow", level: "Patch", ihcTrain: "✗", venue: "Nature Medicine", date: "2024.07", ssl: "DINOv2", arch: "ViT-H/14", params: "632M", wsis: "1.5M", url: "https://www.nature.com/articles/s41591-024-03141-0"},
        { name: "Virchow2", level: "Patch", ihcTrain: "✓", venue: "arXiv", date: "2024.09", ssl: "DINOv2", arch: "ViT-H/14", params: "632M", wsis: "3.1M", url: "https://arxiv.org/abs/2408.00738"},
        { name: "GigaPath", level: "Patch", ihcTrain: "✗", venue: "Nature", date: "2024.05", ssl: "DINOv2", arch: "ViT-G/14", params: "1.1B", wsis: "171K", url: "https://www.nature.com/articles/s41586-024-07441-w"},
        { name: "CTransPath", level: "Patch", ihcTrain: "✗", venue: "Nature", date: "2024.09", ssl: "Swin-T/14", arch: "Swin-T/14", params: "27.8M", wsis: "30K", url: "https://www.sciencedirect.com/science/article/abs/pii/S1361841522002043"},
        { name: "H-optimus-0", level: "Patch", ihcTrain: "✗", venue: "Open-source (GitHub)", date: "2024.08", ssl: "DINOv2", arch: "ViT-G/14", params: "1.1B", wsis: "500K", url: "https://huggingface.co/bioptimus/H-optimus-0"},
        { name: "Phikon", level: "Patch", ihcTrain: "✗", venue: "arXiv", date: "2023.07", ssl: "iBOT", arch: "ViT-B/16", params: "86.4M", wsis: "6K", url: "https://huggingface.co/owkin/Phikon"},
        { name: "GPFM", level: "Patch", ihcTrain: "✗", venue: "Nature Biomedical Engineering", date: "2025.04", ssl: "Custom", arch: "ViT-L/14", params: "303M", wsis: "72.3K", url: "https://www.nature.com/articles/s41551-025-01488-4"},
        { name: "CONCH", level: "Patch", ihcTrain: "✓", venue: "Nature Medicine", date: "2024.03", ssl: "iBOT → CoCa", arch: "ViT-B/16", params: "86M", wsis: "21.4K → 1.2M", url: "https://www.nature.com/articles/s41591-024-02856-4"},
        { name: "CONCH v1.5", level: "Patch", ihcTrain: "✓", venue: "Open-source (GitHub)", date: "2024.09", ssl: "iBOT → CoCa", arch: "ViT-L/16", params: "306M", wsis: "1.17M", url: "#"},
        { name: "Prov-GigaPath", level: "WSI", ihcTrain: "✗", venue: "Nature", date: "2024.05", ssl: "MAE", arch: "Long-context Transformer", params: "85.1M", wsis: "500K", url: "https://www.nature.com/articles/s41586-024-07441-w"},
        { name: "CHIEF", level: "WSI", ihcTrain: "✗", venue: "Nature", date: "2024.09", ssl: "-", arch: "Attention-based MIL/14", params: "1.2M", wsis: "60K", url: "https://pubmed.ncbi.nlm.nih.gov/39232164/"},
        { name: "TITAN", level: "WSI", ihcTrain: "✓", venue: "Nature Medicine", date: "2024.09", ssl: "iBOT → CoCa", arch: "ViT-L/16", params: "6.4M", wsis: "336K", url: "https://arxiv.org/abs/2411.19666"},
        { name: "MADELEINE", level: "WSI", ihcTrain: "✓", venue: "ECCV", date: "2024.08", ssl: "-", arch: "Multi-head Attention-based MIL", params: "5M", wsis: "16.3K", url: "https://arxiv.org/abs/2408.02859"}
      ],

      // Datasets
      datasets: {
        public: [
          { name: "HE-Ki67", stain: "HE, Ki67", disease: "Testicular Cancer", patients: "77", volume: "154 WSIs", url: "https://zenodo.org/records/11218961"},
          { name: "IHC4BC", stain: "HE, ER, PR, Ki67", disease: "Breast Cancer", patients: "240", volume: "92,413 Patches", url: "https://ihc4bc.github.io/"},
          { name: "BCI", stain: "HE, HER2", disease: "Breast Cancer", patients: "--", volume: "9,746 Patches", url: "https://bupt-ai-cz.github.io/BCI/"},
          { name: "HANCOCK", stain: "HE, CD3, CD8, CD56, CD68, CD163, MHC1, PD-L1", disease: "Head and Neck Cancer", patients: "727", volume: "10,330 WSIs", url: "https://github.com/ankilab/HANCOCK_MultimodalDataset?tab=readme-ov-file#dataset"},
          { name: "IMPRESS-DATA", stain: "HE, PD-L1, CD8, CD163", disease: "Breast Cancer", patients: "62", volume: "117 WSIs", url: "https://drive.google.com/drive/folders/1fNf-F_aplm6ACJTWO1vGqbb-DdaP4K_r"},
          { name: "MIHIC", stain: "CD3, CD20, CD34, CD38, CD68, CDK4, Cyclin-D1, D2-40, FAP, Ki67, P53, SMA", disease: "Lung Cancer", patients: "--", volume: "309,698 Patches", url: "https://zenodo.org/records/10065510"},
          { name: "HNSCC", stain: "CD3, CD8, FoxP3, PanCK", disease: "Head and Neck Cancer", patients: "--", volume: "1,336 Patches", url: "https://www.cancerimagingarchive.net/collection/hnscc-mif-mihc-comparison/"},
          { name: "DLBCL-Morph", stain: "HE, BCL2, BCL6, MUM1, MYC", disease: "Lymphoma", patients: "170", volume: "1,009 WSIs", url: "https://www.nature.com/articles/s41597-021-00915-w"},
          { name: "InUIT", stain: "CD8, CD20, Ki67", disease: "Ovarian Cancer", patients: "204", volume: "1,481 WSIs", url: "https://arxiv.org/pdf/2303.00865"},
          { name: "HistAI", stain: "CD20, CD10, CK7, CD34, S100, TTF1, P63, SYN, PAX8, GATA3, PD-L1, P40", disease: "Breast, Skin, Thorax, Hematologic, Gastrointestinal, Colorectal", patients: "1,388", volume: "1,388 WSIs", url: "https://huggingface.co/histai"},
          { name: "MSKMINDProjectM", stain: "PD-L1", disease: "Lung Cancer", patients: "212", volume: "212 WSIs", url: "https://www.synapse.org/Synapse:syn26642505/wiki/615361"},
          { name: "HPA10M", stain: "14,708 Types of Gene-encoded Proteins", disease: "Pan-cancer and Normal Tissues", patients: "3,433", volume: "9,682,431 Images", url: "https://huggingface.co/datasets/nirschl-lab/hpa10m"},
        ],
        private: [
          { name: "CERVIX-CIN", stain: "HE, P16, Ki67", disease: "Cervical Cancer", patients: "175", volume: "488 WSIs"},
          { name: "BREAST-RCB", stain: "HE, ER, GATA3, HER2, Ki67, PR", disease: "Breast Cancer", patients: "87", volume: "440 WSIs"},
          { name: "Lymph-SUB", stain: "HE, CD3, CD5, CD79a, CD21, EBER, CD20", disease: "Hematopoietic and Lymphatic System", patients: "320", volume: "1,875 WSIs"},
          { name: "PANCA-CK56", stain: "CK5/6", disease: "Pan-cancer", patients: "252", volume: "252 WSIs"},
          { name: "PANCA-P63", stain: "P63", disease: "Pan-cancer", patients: "257", volume: "257 WSIs"},
          { name: "PANCA-SYN", stain: "SYN", disease: "Pan-cancer", patients: "275", volume: "275 WSIs"},
          { name: "PANCA-GATA3", stain: "GATA3", disease: "Pan-cancer", patients: "285", volume: "285 WSIs"},
          { name: "PANCA-P16", stain: "P16", disease: "Pan-cancer", patients: "297", volume: "297 WSIs"},
          { name: "PANCA-CD34", stain: "CD34", disease: "Pan-cancer", patients: "464", volume: "464 WSIs"},
          { name: "PANCA-PAX8", stain: "PAX8", disease: "Pan-cancer", patients: "314", volume: "314 WSIs"},
          { name: "PANCA-S100", stain: "S100", disease: "Pan-cancer", patients: "262", volume: "262 WSIs"},
          { name: "PANCA-CK7", stain: "CK7", disease: "Pan-cancer", patients: "192", volume: "192 WSIs"},
          { name: "PANCA-TTF1", stain: "TTF1", disease: "Pan-cancer", patients: "246", volume: "246 WSIs"},
          { name: "PANCA-D2-40", stain: "D2-40", disease: "Pan-cancer", patients: "228", volume: "228 WSIs"},
          { name: "PANCA-Ki67", stain: "Ki67", disease: "Pan-cancer", patients: "568", volume: "568 WSIs"},
          { name: "PANCA-P53", stain: "P53", disease: "Pan-cancer", patients: "226", volume: "226 WSIs"},
          { name: "PANCA-PSA", stain: "PSA", disease: "Pan-cancer", patients: "124", volume: "124 WSIs"},
          { name: "PANCA-AR", stain: "AR", disease: "Pan-cancer", patients: "303", volume: "303 WSIs"},
          { name: "PANCA-ER", stain: "ER", disease: "Pan-cancer", patients: "224", volume: "224 WSIs"},
          { name: "PANCA-PR", stain: "PR", disease: "Pan-cancer", patients: "222", volume: "222 WSIs"},
          { name: "PANCA-PD-L1", stain: "PD-L1", disease: "Pan-cancer", patients: "163", volume: "163 WSIs"},
          { name: "BREAST-HER2", stain: "HER2", disease: "Breast Cancer", patients: "331", volume: "331 WSIs"},
          { name: "PANCA-P40", stain: "P40", disease: "Pan-cancer", patients: "288", volume: "288 WSIs"},
          { name: "PANCA-NAPSINA", stain: "NapsinA", disease: "Pan-cancer", patients: "238", volume: "238 WSIs"},
          { name: "PANCA-CDX2", stain: "CDX2", disease: "Pan-cancer", patients: "165", volume: "165 WSIs"},
          { name: "Lymph-BCL2", stain: "BCL2", disease: "Lymphoma", patients: "159", volume: "159 WSIs"},
          { name: "Lymph-CD10", stain: "CD10", disease: "Lymphoma", patients: "209", volume: "209 WSIs"},
          { name: "Lymph-CD20", stain: "CD20", disease: "Lymphoma", patients: "272", volume: "272 WSIs"},
          { name: "Lymph-EBER", stain: "EBER", disease: "Lymphoma", patients: "234", volume: "234 WSIs"},
        ],
      },
    };

const OVERALL_AUC_RANKING = [
  { model: "Virchow2", score: 0.953 },
  { model: "GPFM", score: 0.952 },
  { model: "UNI", score: 0.950 },
  { model: "Prov-GigaPath", score: 0.948 },
  { model: "H-optimus-0", score: 0.945 },
  { model: "Conch v1.5", score: 0.945 },
  { model: "Conch", score: 0.942 },
  { model: "Phikon", score: 0.940 },
  { model: "CTransPath", score: 0.939 },
  { model: "CHIEF", score: 0.939 },
  { model: "Virchow", score: 0.935 },
  { model: "TITAN (WSI)", score: 0.896 },
  { model: "MADELENE (WSI)", score: 0.879 },
  { model: "CHIEF (WSI)", score: 0.856 },
  { model: "Prov-GigaPath (WSI)", score: 0.794 }
];

const OVERALL_CINDEX_RANKING = [
  { model: "Virchow2", score: 0.591 },
  { model: "TITAN (WSI)", score: 0.584 },
  { model: "Virchow", score: 0.579 },
  { model: "CTransPath", score: 0.573 },
  { model: "GPFM", score: 0.572 },
  { model: "CHIEF", score: 0.570 },
  { model: "H-optimus-0", score: 0.569 },
  { model: "Prov-GigaPath", score: 0.568 },
  { model: "MADELENE (WSI)", score: 0.568 },
  { model: "CHIEF (WSI)", score: 0.567 },
  { model: "Phikon", score: 0.563 },
  { model: "Conch", score: 0.562 },
  { model: "Conch v1.5", score: 0.555 },
  { model: "UNI", score: 0.551 },
  { model: "Prov-GigaPath (WSI)", score: 0.541 }
];
